const bank_whitelist_items = [
    // Core Merch
    "stand0",
	"tracker",
    "mpot1",
    "hpot1",
    "froststaff",
    "broom",
    "iceskates",
    "xmasshoes",
    //"crabclaw",
    //"feather0"

    // Exchangables
    "gem0",
    //"candy0",
    //"candy1",
    //"seashell",
    //"ornament",
    //"mistletoe",
    //"candycane",
    //"armorbox",
    //"weaponbox",
    //"xbox"
]

const crafting_items = {
    crabclaw: {
        base: {
            name: "crabclaw",
            quantity: 1
        },
        component: "claw"
    },
    feather0: {
        base: {
            name: "feather0",
            quantity: 20
        },
        component: "shoes"
    }
}

const upgrade_items = [
    // TEMP
    "mshield",
    //"basher",
    // "rapier",
    // "broom",
    //"wbookhs",
    //"supermittens",
    //"jacko",

    // Belt
    "strbelt",
    "dexbelt",
    "intbelt",

    // Amulet
    "dexamulet",
    "stramulet",
    "intamulet",

    // Earring
    "intearring",
    "strearring",
    "dexearring",

    // Ring
    "strring",
    "intring",
    "dexring",

    // Offhand
    "t2quiver",

    // Helmet
    "wcap",

    // Chest
    "wattire",

    // Gloves
    //"supermittens",

    // Cape
    "angelwings",
    "gcape",

    // Pants
    "pants",
    "wbreeches",

    // Boots
    "wingedboots",
    "wshoes",

    // Weapons
    "firebow",
    "firestaff",
    "fireblade",
    "candycanesword",
    "cclaw"
]

let bots_context = {
    "ryaaahs": {
        "hp_pots": 0,
        "mp_pots" : 0
    },
    "pbuffme": {
        "hp_pots": 0,
        "mp_pots" : 0
    },
    "altfire": {
        "hp_pots": 0,
        "mp_pots" : 0
    }
}

let exchange_table = {
    "seashell": 20,
    "ornament": 20, 
    "candycane": 1,
    "mistletoe": 1,
    "armorbox": 1,
    "weaponbox": 1,
    "xbox": 1,
    "candy0": 1,
    "candy1": 1, 
    "gem0": 1,
}

const whitelist_items = [
  
  // Testing 
  "test",
  "test2",
  "test_orb",
  "placeholder",
  "placeholder_m",

  // Capes
  "stealthcape",
  "cape",
  "fcape",
  "ecape",
  "gcape",
  "angelwings",
  "tigercape",
  "bcape",
  "mcape",
  "vcape",

  // Potions
  "hpot0",
  "mpot0",
  "hpot1",
  "mpot1",
  "hpotx",
  "mpotx",

  // Helmets
  "fury",
  "tigerhelmet",
  "mageshood",
  //"rednose",
  //"helmet",
  "cyber",
  "wcap",
  //"xmashat",
  "ghatb",
  "ghatp",
  //"helmet1",
  "mwhelmet",
  "mmhat",
  "mphat",
  "mrnhat",
  "mrhood",
  "mchat",
  "partyhat",
  //"phelmet",
  //"gphelmet",
  "bunnyears",
  "eears",
  //"hhelmet",
  "xhelmet",
  "spikedhelmet",
  "oxhelmet",

  // Armors
  "luckyt",
  "tshirt0",
  "tshirt1",
  "tshirt2",
  "tshirt3",
  "tshirt4",
  "tshirt88",
  "tshirt6",
  "tshirt7",
  "tshirt8",
  "tshirt9",
  //"coat",
  "wattire",
  //"xmassweater",
  //"sweaterhs",
  //"coat1",
  "mwarmor",
  "mmarmor",
  "mparmor",
  "mrnarmor",
  "mrarmor",
  "mcarmor",
  //"harmor",
  "cdragon",
  "xarmor",
  "vattire",
  "warpvest",

  // Underarmors
  //"pyjamas",
  //"epyjamas",
  "pants",
  "fallen",
  "wbreeches",
  //"xmaspants",
  //"pants1",
  "mwpants",
  "mmpants",
  "mppants",
  "mrnpants",
  "mrpants",
  "mcpants",
  "starkillers",
  //"hpants",
  //"frankypants",
  "xpants",

  // Shoes
  //"shoes",
  "wshoes",
  //"iceskates",
  //"snowboots",
  //"eslippers",
  "wingedboots",
  //"xmasshoes",
  //"shoes1",
  "mwboots",
  "mmshoes",
  "mpshoes",
  "mrnboots",
  "mrboots",
  "mcboots",
  //"hboots",
  "xboots",
  "vboots",

  // Gloves
  //"gloves",
  "vgloves",
  "fierygloves",
  //"wgloves",
  //"mittens",
  "supermittens",
  "powerglove",
  "goldenpowerglove",
  "handofmidas",
  "poker",
  //"gloves1",
  "mpxgloves",
  "mwgloves",
  "mmgloves",
  "mpgloves",
  "mrngloves",
  "mrgloves",
  "mcgloves",
  //"hgloves",
  "xgloves",
  
  //"claw",
  //"cclaw",
  //"throwingstars",
  //"snowflakes",
  //"firestars",
  //"fclaw",
  //"pclaw",
  //"stinger",
  //"dagger",
  "daggerofthedead",
  "dragondagger",
  "hdagger",
  "dartgun",
  "rod",
  "pickaxe",
  //"bow",
  "pouchbow",
  //"weaver",
  //"crossbow",
  //"hbow",
  //"merry",
  //"cupid",
  "firebow",
  //"frostbow",
  //"t2bow",
  "harpybow",
  "t3bow",
  "bowofthedead",
  "gbow",
  "bow4",
  //"spear",
  "spearofthedead",
  "scythe",
  //"blade",
  //"sword",
  //"swifty",
  //"fsword",
  "rapier",
  //"basher",
  "bataxe",
  //"axe3",
  "fireblade",
  "swordofthedead",
  //"woodensword",
  "heartwood",
  //"glolipop",
  //"ololipop",
  //"mace",
  //"xmace",
  //"wbasher",
  // "hammer",
  "vhammer",
  "vstaff",
  "vdagger",
  "vsword",
  "maceofthedead",
  "pmaceofthedead",
  //"carrotsword",
  "candycanesword",
  //"pinkie",
  //"wand",
  "broom",
  //"staff",
  "gstaff",
  "sparkstaff",
  //"staff2",
  //"staff3",
  //"staff4",
  //"slimestaff",
  //"mushroomstaff",
  "firestaff",
  //"ornamentstaff",
  "staffofthedead",
  "froststaff",
  "oozingterror",
  //"harbringer",
  "wblade",
  //"pmace",
  //"lmace",
  
  // Offhands
  //"shield",
  "tigershield",
  "xshield",
  "mshield",
  "exoarm",
  "lantern",
  //"sshield",
  //"wshield",
  //"wbook0",
  //"wbook1",
  "wbookhs",
  //"quiver",
  "t2quiver",
  "alloyquiver",

  // Amulets
  "amuletofm",
  "northstar",
  "bfangamulet",
  "mpxamulet",
  //"skullamulet",
  "spookyamulet",
  //"hpamulet",
  "snring",
  "sanguine",
  "dexamulet",
  "stramulet",
  "intamulet",
  "t2stramulet",
  "t2intamulet",
  "t2dexamulet",
  //"warmscarf",

  // Rings
  "suckerpunch",
  "vring",
  "trigger",
  "zapper",
  "goldring",
  //"armorring",
  //"resistancering",
  "ringofluck",
  "ringhs",
  "tristone",
  "ctristone",
  "darktristone",
  "cdarktristone",
  //"vitring",
  "strring",
  "intring",
  "dexring",
  "cring",
  //"ringsj",
  //"solitaire",


  // Belts
  //"hpbelt",
  "mpxbelt",
  "lbelt",
  "strbelt",
  "mbelt",
  "sbelt",
  //"santasbelt",
  "dexbelt",
  "intbelt",
  
  // Earrings
  "cearring",
  //"molesteeth",
  "mearring",
  "intearring",
  "strearring",
  "dexearring",
  "dexearringx",
  //"vitearring",
  
  // Scrolls 
  "cscroll0",
  "cscroll1",
  "cscroll2",
  "cscroll3",
  "scroll0",
  "scroll1",
  "scroll2",
  "scroll3",
  "scroll4",
  "strscroll",
  "intscroll",
  "dexscroll",
  //"vitscroll",
  "forscroll",
  "evasionscroll",
  "reflectionscroll",
  "goldscroll",
  "luckscroll",
  "xpscroll",
  "armorscroll",
  "resistancescroll",
  "speedscroll",
  "lifestealscroll",
  "manastealscroll",
  "rpiercingscroll",
  "apiercingscroll",
  "critscroll",
  "dreturnscroll",
  "frequencyscroll",
  "mpcostscroll",
  "outputscroll",
  "offering",
  "offeringp",
  "offeringx",
  
  // Orbs
  "orbg",
  "tigerstone",
  "vorb",
  "orbofvit",
  "orbofint",
  "orbofstr",
  "orbofdex",
  "orboffire",
  "orboffrost",
  "orbofplague",
  "orbofresolve",
  "orba",
  "orbofsc",
  "charmer",
  "rabbitsfoot",
  "talkingskull",
  "jacko",
  "ftrinket",

  // Crafting and Collecting / Echangables / Keys / Others

  "cosmo0",
  "cosmo1",
  "cosmo2",
  "cosmo3",
  "cosmo4",
  "stoneofxp",
  "stoneofgold",
  "stoneofluck",
  "xptome",
  "licence",
  "xpbooster",
  "luckbooster",
  "goldbooster",
  "networkcard",
  "qubics",
  "gem0",
  "gem1",
  "gem2",
  "gem3",
  "candypop",
  "candy0",
  "candy1",
  "candy0v2",
  "candy1v2",
  "candy0v3",
  "candy1v3",
  "bugbountybox",
  "apologybox",
  "weaponbox",
  "armorbox",
  "jewellerybox",
  "mistletoe",
  "candycane",
  "gift0",
  "gift1",
  "redenvelope",
  "redenvelopev2",
  "redenvelopev3",
  "redenvelopev4",
  "greenenvelope",
  "essenceoffrost",
  "essenceoffire",
  //"essenceofether",
  "essenceofnature",
  "essenceoflife",
  "essenceofgreed",
  //"emptyjar",
  "cxjar",
  "emotionjar",
  "bottleofxp",
  "nheart",
  "ledger",
  "storagebox",
  "mysterybox",
  "troll",
  //"brownegg",
  //"whiteegg",
  //"gslime",
  "crabclaw",
  //"beewings",
  //"pleather",
  //"spores",
  //"lotusf",
  //"frogt",
  //"snakefang",
  //"rattail",
  //"ascale",
  //"ink",
  //"ijx",
  //"smush",
  //"carrot",
  //"bfur",
  //"bandages",
  //"cocoon",
  //"tshell",
  //"dstones",
  //"bwing",
  //"bfang",
  //"sstinger",
  //"svenom",
  //"pstem",
  //"watercore",
  //"ectoplasm",
  //"rfur",
  //"cshell",
  //"bcandle",
  //"lspores",
  "trinkets",
  //"rfangs",
  "btusk",
  "drapes",
  "stand0",
  "stand1",
  "tracker",
  "computer",
  "supercomputer",
  "stick",
  "coal",
  "glitch",
  "5bucks",
  "confetti",
  "firecrackers",
  // "smoke",
  //"snowball",
  "figurine",
  "pvptoken",
  "funtoken",
  "monstertoken",
  "friendtoken",
  "emptyheart",
  //"fieldgen0",
  //"seashell",
  "leather",
  "gemfragment",
  "ornament",
  "lostearring",
  "stonekey",
  "cryptkey",
  "frozenkey",
  "tombkey",
  "spiderkey",
  "bkey",
  "ukey",
  "dkey",
  "x0",
  "x1",
  "x2",
  "x3",
  "x4",
  "x5",
  "x6",
  "x7",
  "x8",
  "xbox",
  "egg0",
  "egg1",
  "egg2",
  "egg3",
  "egg4",
  "egg5",
  "egg6",
  "egg7",
  "egg8",
  "goldenegg",
  "basketofeggs",
  "frozenstone",
  //"eggnog",
  "vblood",
  //"gum",
  //"hotchocolate",
  //"pumpkinspice",
  //"cake",
  //"greenbomb",
  //"swirlipop",
  "xshot",
  "espresso",
  "whiskey",
  "wine",
  "ale",
  "pico",
  "blue",
  "bunnyelixir",
  //"elixirvit0",
  //"elixirvit1",
  //"elixirvit2",
  //"elixirstr0",
  //"elixirstr1",
  //"elixirstr2",
  //"elixirdex0",
  //"elixirdex1",
  //"elixirdex2",
  //"elixirint0",
  //"elixirint1",
  //"elixirint2",
  "elixirluck",
  "elixirfires",
  "elixirfzres",
  "elixirpnres",
  //"poison",
  "shadowstone",
  "mbones",
  "cscale",
  //"snakeoil",
  "feather0",
  "feather1",
  "bronzeingot",
  "goldingot",
  "platinumingot",
  "bronzenugget",
  "goldnugget",
  "platinumnugget",
  "electronics",
  "spidersilk",
  "flute",
  "puppyer",
  "chrysalis0",
  "puppy1",
  "kitty1",
  "monsterbox"
]